# Generated by Django 6.1 on 2026-08-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'last_name', 'first_name'],
                     'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
