"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=)6yk90s@ongezg0&d40!$l%eav=%4wbyc(*t_+c86#y=mkfb7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # installed apps
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # папка для разработки
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ========== НАСТРОЙКИ DJANGO REST FRAMEWORK (DRF) ==========

REST_FRAMEWORK = {
    # Настройка фильтрации - позволяет фильтровать данные по параметрам запроса
    # Например: /api/posts/?author=1&category=news
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),

    # Настройка аутентификации - использование JWT токенов для авторизации
    # Пользователи получают токен при входе и передают его в заголовке Authorization
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.simplejwt.authentication.JWTAuthentication',),

    # Настройка прав доступа - AllowAny означает, что API доступно всем (даже без регистрации)
    # Для продакшена нужно заменить на IsAuthenticated
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    # 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',), - только для авторизованных
}

# ========== НАСТРОЙКИ JWT ТОКЕНОВ ==========

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    # Время жизни access токена - 1 час (короткий срок для безопасности)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Время жизни refresh токена - 7 дней (долгий срок для удобства)
}

# ========== НАСТРОЙКИ CORS (Cross-Origin Resource Sharing) ==========

CORS_ALLOWED_ORIGINS = [
    'http://read-only.example.com',  # Разрешенный источник - только чтение данных
    'https://read-and-write.example.com',  # Разрешенный источник - чтение и запись данных
]
# Эти домены могут отправлять запросы к вашему API с фронтенда (React, Vue, Angular)


# ========== НАСТРОЙКИ CSRF (Cross-Site Request Forgery) ==========

CSRF_TRUSTED_ORIGINS = [
    'http://read-and-write.example.com',  # Доверенные источники для CSRF-защиты (для форм и админки)
]
# Защита от подделки межсайтовых запросов - важна для Django админки и форм
