# Generated by Django 6.1 on 2026-08-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                 unique=True, verbose_name='title')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                 unique=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='sections.section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['id'],
            },
        ),
    ]
